# Generated by Django 6.0.5 on 2026-05-17 17:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledgers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('voided', 'Voided')], default='paid', max_length=20)),
                ('paid_at', models.DateTimeField()),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='ledgers.resultperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Number must be exactly 3 digits, example: 000, 024, 124, 999.', regex='^\\d{3}$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_generated_by_r', models.BooleanField(default=False)),
                ('source_input', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='receipts.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='PaidNumberAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Number must be exactly 3 digits, example: 000, 024, 124, 999.', regex='^\\d{3}$')])),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('allocation_order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_allocations', to='ledgers.ledger')),
                ('ledger_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_allocations', to='ledgers.ledgernumber')),
                ('receipt_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='receipts.receiptitem')),
            ],
        ),
        migrations.CreateModel(
            name='RGeneratedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_number', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Number must be exactly 3 digits, example: 000, 024, 124, 999.', regex='^\\d{3}$')])),
                ('source_text', models.CharField(max_length=20)),
                ('amount_per_number', models.DecimalField(decimal_places=2, max_digits=18)),
                ('generated_count', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='r_generated_groups', to='receipts.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='RGeneratedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Number must be exactly 3 digits, example: 000, 024, 124, 999.', regex='^\\d{3}$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='receipts.rgeneratedgroup')),
                ('receipt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='r_generated_items', to='receipts.receiptitem')),
            ],
        ),
    ]
