# Generated by Django 6.0.5 on 2026-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('close', 'Close'), ('approve', 'Approve'), ('reject', 'Reject'), ('void', 'Void'), ('login', 'Login'), ('logout', 'Logout'), ('deactivate', 'Deactivate'), ('cashout', 'Cashout'), ('override', 'Override'), ('reserve_deposit', 'Reserve Deposit'), ('settlement', 'Settlement'), ('result_entry', 'Result Entry'), ('password_reset', 'Password Reset')], max_length=40),
        ),
    ]
