# Generated by Django 6.0.5 on 2026-05-17 16:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity_per_number', models.DecimalField(decimal_places=2, max_digits=18)),
                ('settlement_rate', models.DecimalField(decimal_places=2, default=Decimal('700.00'), max_digits=18)),
                ('priority_order', models.PositiveIntegerField()),
                ('open_at', models.DateTimeField()),
                ('close_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('settled', 'Settled'), ('archived', 'Archived')], default='open', max_length=20)),
                ('manually_closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ledgers', to=settings.AUTH_USER_MODEL)),
                ('manually_closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manually_closed_ledgers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['result_period', 'priority_order'],
            },
        ),
        migrations.CreateModel(
            name='LedgerPriorityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_priority', models.PositiveIntegerField(blank=True, null=True)),
                ('new_priority', models.PositiveIntegerField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changed_ledger_priorities', to=settings.AUTH_USER_MODEL)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='priority_history', to='ledgers.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='ResultPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('result_date', models.DateField()),
                ('default_close_time', models.TimeField()),
                ('result_number', models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='Number must be exactly 3 digits, example: 000, 024, 124, 999.', regex='^\\d{3}$')])),
                ('result_source', models.CharField(choices=[('manual', 'Manual'), ('api_imported', 'API Imported'), ('api_checked_manual_confirmed', 'API Checked + Manual Confirmed')], default='manual', max_length=50)),
                ('is_visible_to_users', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('result_entered', 'Result Entered'), ('settlement_previewed', 'Settlement Previewed'), ('funding_required', 'Funding Required'), ('ready_to_approve', 'Ready To Approve'), ('settlement_approved', 'Settlement Approved'), ('settled', 'Settled'), ('archived', 'Archived')], default='open', max_length=40)),
                ('result_entered_at', models.DateTimeField(blank=True, null=True)),
                ('result_voided_at', models.DateTimeField(blank=True, null=True)),
                ('result_void_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_result_periods', to=settings.AUTH_USER_MODEL)),
                ('result_entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entered_results', to=settings.AUTH_USER_MODEL)),
                ('result_voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ledger',
            name='result_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='ledgers.resultperiod'),
        ),
        migrations.CreateModel(
            name='LedgerNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Number must be exactly 3 digits, example: 000, 024, 124, 999.', regex='^\\d{3}$')])),
                ('max_capacity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('used_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numbers', to='ledgers.ledger')),
            ],
            options={
                'ordering': ['ledger', 'number_code'],
                'unique_together': {('ledger', 'number_code')},
            },
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['result_period', 'priority_order'], name='ledgers_led_result__ce4617_idx'),
        ),
    ]
