# Generated by Django 6.0.5 on 2026-05-17 17:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledgers', '0001_initial'),
        ('receipts', '0001_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_number', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Number must be exactly 3 digits, example: 000, 024, 124, 999.', regex='^\\d{3}$')])),
                ('total_collected', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_settlement', models.DecimalField(decimal_places=2, max_digits=18)),
                ('company_reserve_required', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('company_reserve_used', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('final_profit_loss', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('previewed', 'Previewed'), ('funding_required', 'Funding Required'), ('approved', 'Approved'), ('paid', 'Paid'), ('voided', 'Voided')], default='previewed', max_length=30)),
                ('previewed_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_settlement_batches', to=settings.AUTH_USER_MODEL)),
                ('previewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='previewed_settlement_batches', to=settings.AUTH_USER_MODEL)),
                ('result_period', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_batch', to='ledgers.resultperiod')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_settlement_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SettlementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Number must be exactly 3 digits, example: 000, 024, 124, 999.', regex='^\\d{3}$')])),
                ('total_matched_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('settlement_rate', models.DecimalField(decimal_places=2, max_digits=18)),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('previewed', 'Previewed'), ('funding_required', 'Funding Required'), ('approved', 'Approved'), ('paid', 'Paid'), ('voided', 'Voided')], default='previewed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='settlements.settlementbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_items', to=settings.AUTH_USER_MODEL)),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_items', to='wallets.wallettransaction')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementItemSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('receipt_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_sources', to='receipts.receiptitem')),
                ('settlement_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='settlements.settlementitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='settlementitem',
            index=models.Index(fields=['settlement_batch', 'user', 'number_code'], name='settlements_settlem_701aa0_idx'),
        ),
    ]
